[package]
name = "rust-ownership"
version = "0.1.0"
authors = ["Kevin W Matthews <KevinWMatthews@gmail.com>"]
edition = "2018"

[dependencies]

[[bin]]
name = "mutable_reference_scope"
path = "src/mutable_reference_scope.rs"
