# theme: minima
remote_theme: KevinWMatthews/minima
title: rust/ownership
author: Kevin W Matthews
author_url: https://www.kevinwmatthews.com
description:
  Ownership in Rust
header_pages:
  - setup.md
github_username: KevinWMatthews
linkedin_username: KevinWMatthews
